name: Replication 1
on: push
jobs:
  replicate-to-gitlab:
    runs-on: ubuntu-latest
    steps:
      # Show push info
      - run: echo "Author name is ${{ github.event.head_commit.author.name }}"
      - run: echo "Author email is ${{ github.event.head_commit.author.email }}"
      # - run: echo "Commit message is ${{ github.event.head_commit.message }}"
      # - uses: actions/checkout@v3
      #   with:
      #     repository: https://gitlab.com/EmmanuelDgz/repository-container.git
      #     path: all_modules
      # Clone current repo
      - uses: actions/checkout@v3
        with:
          path: actions1
      # Delete unnecessary files from current repo
      - run: rm -rf actions1/.git/ actions1/.github/ actions1/.gitignore actions1/README.md
      # Clone remote gitlab repository container
      - run: git clone https://gitlab.com/EmmanuelDgz/repository-container.git all_modules
      # Put all files from current repo into repository container
      - run: mkdir -p all_modules/module1
      - run: mv actions1/* all_modules/module1/
      - run: ls -la all_modules
