name: Replication 1
on: push
jobs:
  replicate-to-gitlab:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Author name is ${{ github.event.head_commit.author.name }}"
      - run: echo "Author email is ${{ github.event.head_commit.author.email }}"
      - run: echo "Commit message is ${{ github.event.head_commit.message }}"
