name: actions1 replication
on: push
jobs:
  replicate-to-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Show committer info
        run: |
          echo "Author name is ${{ github.event.head_commit.author.name }}"
          echo "Author email is ${{ github.event.head_commit.author.email }}"
          echo "Commit message is ${{ github.event.head_commit.message }}"
      - name: Checkout actions1 repo
        uses: actions/checkout@v3
        with:
          path: actions1
      - name: Remove actions1 repo unnecessary files
        run: rm -rf actions1/.git/ actions1/.github/ actions1/.gitignore actions1/README.md
      - name: Checkout repository-container repo
        uses: actions/checkout@v3
        with:
          repository: EmmanuelDgz/repository-container
          ref: develop
          path: all_modules
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy changes into local repository-container
        run: |
          # actions1 repo is expected to hold files only, they all define a module
          mkdir -p all_modules/module1
          cp actions1/* all_modules/module1/
      - name: Push changes into remote repository-container
        run: |
          cd all_modules
          git status
          git config --global user.name "actions1"
          git config --global user.email "actions1@github.com"
          git add .
          git commit -m "${{ github.event.head_commit.message }}"
          git push
